# Generated by Django 4.2.3 on 2023-07-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='provincee',
            new_name='province',
        ),
    ]
