# Generated by Django 4.2.3 on 2023-07-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp2', '0002_rename_provincee_record_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='country',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
